run:
  timeout: 5m
  tests: true

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - goconst
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam
    - whitespace
    # - gocyclo # Cyclomatic complexity - can be noisy for existing code
    - gosec   # Security checker

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: easyConfig
  misspell:
    locale: US
  whitespace:
    multi-if: false # Enforces newlines (or not) in multi-line if conditions
    multi-func: false # Enforces newlines (or not) in multi-line function signatures

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-dirs:
    - build
    - frontend
    - wailsjs
