// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export const config = {
  Item: class {
    constructor(source) {
      this.provider = source["provider"];
      this.name = source["name"];
      this.fileName = source["fileName"];
      this.path = source["path"];
      this.scope = source["scope"];
      this.format = source["format"];
      this.exists = source["exists"];
    }
  },
};
