// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {marketplaces} from '../models';

export function CreateConfig(arg1:string,arg2:string,arg3:string):Promise<string>;

export function DeleteConfig(arg1:string):Promise<void>;

export function DiscoverConfigs(arg1:string):Promise<Array<config.Item>>;

export function FetchPopularServers():Promise<Array<marketplaces.MCPPackage>>;

export function FetchSchemas():Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function InstallMCPPackage(arg1:marketplaces.MCPPackage):Promise<void>;

export function ReadConfig(arg1:string):Promise<string>;

export function SaveConfig(arg1:string,arg2:string):Promise<void>;
