// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import {config} from '../config/models';

export function Greet(arg1: string): Promise<string>;

export function DiscoverConfigs(arg1: string): Promise<Array<config.ConfigItem>>;
