// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {marketplaces} from '../models';
import {workflows} from '../models';

export function ApplyProfile(arg1:string):Promise<Array<string>>;

export function CreateConfig(arg1:string,arg2:string,arg3:string):Promise<string>;

export function DeleteConfig(arg1:string):Promise<void>;

export function DeleteProfile(arg1:string):Promise<void>;

export function DiscoverConfigs(arg1:string):Promise<Array<config.Item>>;

export function FetchPopularServers():Promise<Array<marketplaces.MCPPackage>>;

export function FetchSchemas():Promise<void>;

export function GenerateWorkflow(arg1:string,arg2:string):Promise<workflows.WorkflowResponse>;

export function GetProfileContent(arg1:string,arg2:string):Promise<string>;

export function GetProviderStatuses():Promise<Array<config.ProviderStatus>>;

export function GetSupportedWorkflows():Promise<Array<string>>;

export function Greet(arg1:string):Promise<string>;

export function InstallMCPPackage(arg1:string):Promise<void>;

export function ListDocs():Promise<Array<config.DocsProvider>>;

export function ListProfileFiles(arg1:string):Promise<Array<config.ProfileItem>>;

export function ListProfiles():Promise<Array<config.ProfileSummary>>;

export function ListWorkflowTemplates():Promise<Array<workflows.Template>>;

export function ReadConfig(arg1:string):Promise<string>;

export function ReadDoc(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SaveConfig(arg1:string,arg2:string):Promise<void>;

export function SaveProfile(arg1:string):Promise<void>;

export function SaveWorkflow(arg1:string,arg2:string):Promise<void>;

export function SearchAll(arg1:string,arg2:config.SearchOptions):Promise<Array<config.SearchResult>>;

export function SetSecret(arg1:string,arg2:string):Promise<void>;
