// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateConfig(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateConfig'](arg1, arg2, arg3);
}

export function DiscoverConfigs(arg1) {
  return window['go']['main']['App']['DiscoverConfigs'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ReadConfig(arg1) {
  return window['go']['main']['App']['ReadConfig'](arg1);
}

export function SaveConfig(arg1, arg2) {
  return window['go']['main']['App']['SaveConfig'](arg1, arg2);
}